export const COLOR = {
  green1: '#1868ae',
  // green1: 'rgba(0,190,212,1)',
  green_pale: '#1868ae',
  blue1: '#009EFD',
  primary: 'blue',
  background: '#eceff2',
  primary: '#11ca71',
  primary2: '#47AA12',
  warning: '#FF2E00',
  danger: '#FF2E00',
  success: '#00EFEF',
  toggle: '#94D213',
  link: '#0055FF',
  default: '#787878',
  text: '#383838',
  card: '#dbdfe2',
  border: '#9c9c9c',
  title: '#005920',
  info: '#0073FF',
  note: '#002570',


  color_tabbar: '#fff',
  icon_open: '#1868ae',
  icon_close: '#9C9B97',
  backgroundInput: '#ffffff',
  textBadge: '#fff',
  bgBadge: 'red',
  bgAlert: '#0295F0',
  titAlert: '#000',
  contAlert: '#000',
  noAlert: '#007AFF',
  yesAlert: '#007AFF',
}

export const COLOR_APP = {
  placeholder:'#B8C4D1',
  text_input: '#798EA9',
  icon_input: '#26D1FE',
  backgroundInput: '#ffffff',
  textBadge: '#fff',
  bgBadge: 'red',
  bgAlert: '#0295F0',
  titAlert: '#fff',
  contAlert: '#fff',
  noAlert: '#000',
  yesAlert: '#00FF7F',
}
export const FSIZE = {
  fs14: 14,
  fs16: 16,
  fs18: 18,
  fs20: 20,
  fs22: 22,
  fsTitleHeader: 18,
}
export const ICON={
  eye:'',
  menu:'menu',
  mail_outline:'mail-outline',
  mail:'mail',
  lock_closed_outline:'lock-closed-outline',
  lock_closed:'lock-closed',
  calendar_number:'calendar-number',
  receipt:'receipt',
  volume_high:'volume-high',
  arrow_back:'arrow-back-outline',
  chevron_back_outline:'chevron-back-outline',
  checkbox:'checkbox',
  bookmark:'bookmark',
  notifications:'notifications',
  person_circle:'person-circle',
  person:'person',
  settings:'settings',
  key:'key',
  log_out:'log-out',
  arrow_up_circle_outline:'arrow-up-circle-outline',
  close_outline:'close-outline'

}